
server:
  port: 9000
spring:
  application:
    name: board-article-service
  datasource:
    hikari:
      data-source-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/article
      username: root
      password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
