server:
  port: 9003
spring:
  application:
    name: board-view-service
  datasource:
    url: jdbc:mysql://localhost:3306/article_view
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092
