spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lecture-db
  graphql:
    schema:
      locations: classpath:graphql/
jwt:
  secret: rlfdlsmsrlfrpwnjdigkqslekchlth200dltkddmswnjdigksmsrjrkxdmsep200dms200wksmsdkslqslek