spring:
  application:
    name: splearn
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
  docker:
    compose:
      lifecycle-management: start_only