spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console