version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gradualy1!
      MYSQL_DATABASE: gi-db
      MYSQL_USER: gi-user
      MYSQL_PASSWORD: gradualy1!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  