server:
  port: 9001
spring:
  application:
    name: board-comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/comment
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
