name: Update submodule references

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout personal-lab with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_LAB_PAT }}

      - name: Update submodules
        run: |
          git submodule update --remote --checkout

      - name: Commit and push submodule changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # 커밋할 변경이 없으면 건너뜀
          git add go-lab cpp-lab
          git diff --cached --quiet && echo "No submodule updates" && exit 0
          
          git commit -m "ch
